# Generated by Django 3.2.9 on 2021-12-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211202_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_twiter',
            new_name='social_twitter',
        ),
    ]
