# Generated by Django 3.2.9 on 2021-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20211002_1859"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feature_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
